### ISSUE TITLE
data from different sources

### ISSUE THREAD

**Issue by ctsjyyk** [EvaYiwenWang/PLSDAbatch#3]
Hello! I am fortunate to have read your article. But I have some questions. I downloaded some human metagenomic data from the internet, intending to use it for unified analysis. However, there is clearly a batch effect issue, so I want to use PASILLA batch for analysis. However, is this type of data from different sources suitable for using PASILLA batch?

**Comment by EvaYiwenWang** [comment]
Hello,

First of all, the data from different sources should have same microbial variables. If they are different, you may need to choose either to select the overlapped variables, or duplicate the unique variables to other datasets. Secondly, you need to ensure that the treatments occur consistently in each batch; otherwise, you may obtain spurious results. Feel free to discuss any issues you encounter when analysing data.

Best of Luck!
Eva
